/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

import classes.Gerente;
import static telas.cadastarGerente.listaGerente;

/**
 *
 * @author Yuri
 */
public class areaGerente extends javax.swing.JFrame {

    /**
     * Creates new form areaGerente
     */
    public areaGerente() {
        initComponents();
        
        setLocationRelativeTo(null);
        disableGerenteFields();
        disableControleFuncionariosButtons();
        disableControleFuncionariosFields();
        
        btnCancelarGerente.setEnabled(false);
        btnSalvarGerente.setEnabled(false);
        btnAlterarGerente.setEnabled(true);
        
        btnNovoFuncionario.setEnabled(true);
        //btnPesquisarFuncionario.setEnabled(true);
        loadGerenteInfo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    public void loadGerenteInfo(){
        Gerente gerente1 = listaGerente.get(0);
        txtNomeGerente.setText(gerente1.getNome());
        ftxCPFGerente.setText(gerente1.getCPF());
        txtEmailGerente.setText(gerente1.getEmail());
        txtSenhaGerente.setText(gerente1.getSenha());
        txtIdGerente.setText(gerente1.getCadastroGerente());
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        lblAreaGerente = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblNomeGerente = new javax.swing.JLabel();
        lblCPFGerente = new javax.swing.JLabel();
        lblEmailGerente = new javax.swing.JLabel();
        lblSenhaGerente = new javax.swing.JLabel();
        lblIdGerente = new javax.swing.JLabel();
        txtNomeGerente = new javax.swing.JTextField();
        txtEmailGerente = new javax.swing.JTextField();
        txtSenhaGerente = new javax.swing.JTextField();
        txtIdGerente = new javax.swing.JTextField();
        ftxCPFGerente = new javax.swing.JFormattedTextField();
        lblDadosGerente = new javax.swing.JLabel();
        btnAlterarGerente = new javax.swing.JButton();
        btnSalvarGerente = new javax.swing.JButton();
        btnCancelarGerente = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lblNomeFuncionario = new javax.swing.JLabel();
        lblCPFFuncionario = new javax.swing.JLabel();
        lblIdFuncionario = new javax.swing.JLabel();
        txtNomeFuncionario = new javax.swing.JTextField();
        txtCodigoFuncionario = new javax.swing.JTextField();
        btnNovoFuncionario = new javax.swing.JButton();
        btnBuscarFuncionario = new javax.swing.JButton();
        ftxCPFFuncionario = new javax.swing.JFormattedTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblControleFuncionariosx = new javax.swing.JTable();
        btnSalvarFuncionario = new javax.swing.JButton();
        btnExcluirFuncionario = new javax.swing.JButton();
        lblControleFuncionarios = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Área do Gerente");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblAreaGerente.setFont(new java.awt.Font("Old English Text MT", 1, 48)); // NOI18N
        lblAreaGerente.setText("Dados do Gerente");
        getContentPane().add(lblAreaGerente, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 160, -1, -1));

        jPanel1.setBackground(new java.awt.Color(211, 181, 143));

        lblNomeGerente.setFont(new java.awt.Font("Old English Text MT", 1, 36)); // NOI18N
        lblNomeGerente.setText("Nome");

        lblCPFGerente.setFont(new java.awt.Font("Old English Text MT", 0, 36)); // NOI18N
        lblCPFGerente.setText("CPF");

        lblEmailGerente.setFont(new java.awt.Font("Old English Text MT", 0, 36)); // NOI18N
        lblEmailGerente.setText("E-mail");

        lblSenhaGerente.setFont(new java.awt.Font("Old English Text MT", 0, 36)); // NOI18N
        lblSenhaGerente.setText("Senha");

        lblIdGerente.setFont(new java.awt.Font("Old English Text MT", 0, 36)); // NOI18N
        lblIdGerente.setText("Id Gerente");

        txtNomeGerente.setFont(new java.awt.Font("Old English Text MT", 0, 24)); // NOI18N
        txtNomeGerente.setToolTipText("insira o nome");
        txtNomeGerente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeGerenteActionPerformed(evt);
            }
        });

        txtEmailGerente.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtEmailGerente.setToolTipText("insira o e-mail");

        txtSenhaGerente.setToolTipText("defina uma senha");

        txtIdGerente.setFont(new java.awt.Font("Old English Text MT", 0, 24)); // NOI18N
        txtIdGerente.setToolTipText("defina um Id Gerente");

        try {
            ftxCPFGerente.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ftxCPFGerente.setToolTipText("insira o CPF");

        lblDadosGerente.setFont(new java.awt.Font("Old English Text MT", 1, 60)); // NOI18N
        lblDadosGerente.setText("Dados do Gerente");

        btnAlterarGerente.setBackground(new java.awt.Color(255, 255, 0));
        btnAlterarGerente.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnAlterarGerente.setText("Alterar");
        btnAlterarGerente.setToolTipText("alterar os dados já existentes");
        btnAlterarGerente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarGerenteActionPerformed(evt);
            }
        });

        btnSalvarGerente.setBackground(new java.awt.Color(0, 255, 0));
        btnSalvarGerente.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnSalvarGerente.setText("Salvar");
        btnSalvarGerente.setToolTipText("Salvar os dados");
        btnSalvarGerente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarGerenteActionPerformed(evt);
            }
        });

        btnCancelarGerente.setBackground(new java.awt.Color(255, 0, 0));
        btnCancelarGerente.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnCancelarGerente.setText("Cancelar");
        btnCancelarGerente.setToolTipText("Cancelar a operação");
        btnCancelarGerente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarGerenteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lblCPFGerente)
                        .addGap(218, 218, 218))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lblEmailGerente)
                        .addGap(209, 209, 209))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtSenhaGerente, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtEmailGerente, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ftxCPFGerente, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtNomeGerente)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(213, 213, 213)
                        .addComponent(lblNomeGerente)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(txtIdGerente)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(217, 217, 217)
                                .addComponent(lblSenhaGerente))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(184, 184, 184)
                                .addComponent(lblIdGerente)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAlterarGerente)
                .addGap(136, 136, 136)
                .addComponent(btnSalvarGerente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCancelarGerente)
                .addGap(20, 20, 20))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(lblDadosGerente)
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblDadosGerente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNomeGerente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNomeGerente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblCPFGerente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ftxCPFGerente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblEmailGerente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtEmailGerente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(lblSenhaGerente)
                .addGap(18, 18, 18)
                .addComponent(txtSenhaGerente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(lblIdGerente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtIdGerente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAlterarGerente)
                    .addComponent(btnSalvarGerente)
                    .addComponent(btnCancelarGerente))
                .addGap(102, 102, 102))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, 530, 670));

        jPanel2.setBackground(new java.awt.Color(211, 181, 143));

        lblNomeFuncionario.setFont(new java.awt.Font("Old English Text MT", 0, 18)); // NOI18N
        lblNomeFuncionario.setText("Nome");

        lblCPFFuncionario.setFont(new java.awt.Font("Old English Text MT", 0, 18)); // NOI18N
        lblCPFFuncionario.setText("CPF");

        lblIdFuncionario.setFont(new java.awt.Font("Old English Text MT", 0, 18)); // NOI18N
        lblIdFuncionario.setText("Código de funcionário");

        txtNomeFuncionario.setToolTipText("insira o nome do funcionario");

        txtCodigoFuncionario.setToolTipText("insira o código do funcionário");
        txtCodigoFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoFuncionarioActionPerformed(evt);
            }
        });

        btnNovoFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/simbolos/add_icon-icons.com_74429 (2).png"))); // NOI18N
        btnNovoFuncionario.setText("Novo");
        btnNovoFuncionario.setToolTipText("Adicionar novo funcionário");
        btnNovoFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoFuncionarioActionPerformed(evt);
            }
        });

        btnBuscarFuncionario.setFont(new java.awt.Font("Old English Text MT", 0, 18)); // NOI18N
        btnBuscarFuncionario.setText("Buscar");
        btnBuscarFuncionario.setToolTipText("Buscar pelo funcionário");

        try {
            ftxCPFFuncionario.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ftxCPFFuncionario.setToolTipText("insira o CPF do funcionário");

        tblControleFuncionariosx.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nome", "CPF", "E-mail", "Senha", "Cód. Funcionário"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblControleFuncionariosx.setToolTipText("Tabela com os dados de funcionários");
        jScrollPane1.setViewportView(tblControleFuncionariosx);

        btnSalvarFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/simbolos/Save_37110.png"))); // NOI18N
        btnSalvarFuncionario.setText("Salvar");
        btnSalvarFuncionario.setToolTipText("Salvar dados do funcionário");
        btnSalvarFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarFuncionarioActionPerformed(evt);
            }
        });

        btnExcluirFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/simbolos/delete_4219.png"))); // NOI18N
        btnExcluirFuncionario.setText("Excluir");
        btnExcluirFuncionario.setToolTipText("excluir funcionário");

        lblControleFuncionarios.setFont(new java.awt.Font("Old English Text MT", 1, 48)); // NOI18N
        lblControleFuncionarios.setText("Controle de funcionários");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(171, 171, 171)
                .addComponent(lblControleFuncionarios)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(btnNovoFuncionario)
                .addGap(184, 184, 184)
                .addComponent(btnSalvarFuncionario)
                .addGap(170, 170, 170)
                .addComponent(btnExcluirFuncionario)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNomeFuncionario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNomeFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(lblCPFFuncionario)
                .addGap(18, 18, 18)
                .addComponent(ftxCPFFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(lblIdFuncionario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCodigoFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addComponent(btnBuscarFuncionario)
                .addGap(15, 15, 15))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblControleFuncionarios)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblNomeFuncionario)
                        .addComponent(lblCPFFuncionario)
                        .addComponent(ftxCPFFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblIdFuncionario)
                        .addComponent(txtCodigoFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnBuscarFuncionario))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtNomeFuncionario)
                        .addGap(1, 1, 1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNovoFuncionario)
                    .addComponent(btnSalvarFuncionario)
                    .addComponent(btnExcluirFuncionario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 220, 870, 430));

        jPanel3.setBackground(new java.awt.Color(211, 181, 143));

        jLabel2.setFont(new java.awt.Font("Old English Text MT", 1, 36)); // NOI18N
        jLabel2.setText("Controle de Clientes");

        jLabel3.setFont(new java.awt.Font("Old English Text MT", 0, 18)); // NOI18N
        jLabel3.setText("Nome");

        jLabel4.setFont(new java.awt.Font("Old English Text MT", 0, 18)); // NOI18N
        jLabel4.setText("CPF");

        jLabel5.setFont(new java.awt.Font("Old English Text MT", 0, 18)); // NOI18N
        jLabel5.setText("Código de Cliente");

        jButton1.setFont(new java.awt.Font("Old English Text MT", 0, 18)); // NOI18N
        jButton1.setText("Buscar");

        jButton2.setText("Novo");

        jButton3.setText("Salvar");

        jButton4.setText("Excluir");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(253, 253, 253))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addComponent(jButton2)
                .addGap(213, 213, 213)
                .addComponent(jButton3)
                .addGap(143, 143, 143)
                .addComponent(jButton4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addGap(0, 293, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 670, 940, 390));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ÁreaGerente.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, 1920, 1140));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomeGerenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeGerenteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeGerenteActionPerformed

    private void btnAlterarGerenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarGerenteActionPerformed
        // TODO add your handling code here:
        enableGerenteFields();
        btnAlterarGerente.setEnabled(false);
        btnSalvarGerente.setEnabled(true);
        btnCancelarGerente.setEnabled(true);
    }//GEN-LAST:event_btnAlterarGerenteActionPerformed

    private void btnSalvarGerenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarGerenteActionPerformed
        // TODO add your handling code here:
        disableGerenteFields();
        btnAlterarGerente.setEnabled(true);
        btnSalvarGerente.setEnabled(false);
        btnCancelarGerente.setEnabled(false);
    }//GEN-LAST:event_btnSalvarGerenteActionPerformed

    private void btnCancelarGerenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarGerenteActionPerformed
        // TODO add your handling code here:
        disableGerenteFields();
        btnAlterarGerente.setEnabled(true);
        btnSalvarGerente.setEnabled(false);
        btnCancelarGerente.setEnabled(false);
    }//GEN-LAST:event_btnCancelarGerenteActionPerformed

    private void btnSalvarFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarFuncionarioActionPerformed
        // TODO add your handling code here:
        disableControleFuncionariosFields();
        disableControleFuncionariosButtons();
        btnNovoFuncionario.setEnabled(true);
        //btnPesquisarFuncionario.setEnabled(true);
    }//GEN-LAST:event_btnSalvarFuncionarioActionPerformed

    private void btnNovoFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoFuncionarioActionPerformed
        // TODO add your handling code here:
        //enableControleFuncionariosFields();
        disableControleFuncionariosButtons();
        btnSalvarFuncionario.setEnabled(true);
        //btnCancelarFuncionario.setEnabled(true);
        new cadastrarFuncionario().setVisible(true);
    }//GEN-LAST:event_btnNovoFuncionarioActionPerformed

    private void txtCodigoFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoFuncionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoFuncionarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(areaGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(areaGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(areaGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(areaGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new areaGerente().setVisible(true);
                
            }
        });
    }
    
    public void disableGerenteFields(){
        txtNomeGerente.setEnabled(false);
        ftxCPFGerente.setEnabled(false);
        txtEmailGerente.setEnabled(false);
        txtSenhaGerente.setEnabled(false);
        txtIdGerente.setEnabled(false);
        
        lblNomeGerente.setEnabled(false);
        lblCPFGerente.setEnabled(false);
        lblEmailGerente.setEnabled(false);
        lblSenhaGerente.setEnabled(false);
        lblIdGerente.setEnabled(false);
    }
    
    public void enableGerenteFields(){
        txtNomeGerente.setEnabled(true);
        ftxCPFGerente.setEnabled(true);
        txtEmailGerente.setEnabled(true);
        txtSenhaGerente.setEnabled(true);
        txtIdGerente.setEnabled(true);
        
        lblNomeGerente.setEnabled(true);
        lblCPFGerente.setEnabled(true);
        lblEmailGerente.setEnabled(true);
        lblSenhaGerente.setEnabled(true);
        lblIdGerente.setEnabled(true);
        
    }
    
    public void disableControleFuncionariosButtons(){
        btnNovoFuncionario.setEnabled(false);
        btnSalvarFuncionario.setEnabled(false);
        //btnCancelarFuncionario.setEnabled(false);
        btnExcluirFuncionario.setEnabled(false);
        //btnPesquisarFuncionario.setEnabled(false);
        btnBuscarFuncionario.setEnabled(false);

    }
    
    public void disableControleFuncionariosFields(){
        //NUNCA DEIXE O TXTCODIGOFUNCIONARIO COMO ENABLED=TRUE. CASO ISSO SEJA FEITO E O ÍNDICE DO FUNCIONÁRIO SEJA MUDADO PARA UM VALOR JÁ EXISTENTE, ENTÃO O SISTEMA QUEBRA
        txtNomeFuncionario.setEnabled(false);
        ftxCPFFuncionario.setEnabled(false);
        //txtEmailFuncionario.setEnabled(false);
        //txtSenhaFuncionario.setEnabled(false);
        txtCodigoFuncionario.setEnabled(false);
        
        lblNomeFuncionario.setEnabled(false);
        lblCPFFuncionario.setEnabled(false);
        //lblEmailFuncionario.setEnabled(false);
        //lblSenhaFuncionario.setEnabled(false);
        lblIdFuncionario.setEnabled(false);
        
    }
    
    public void enableControleFuncionariosFields(){
        //NUNCA DEIXE O TXTCODIGOFUNCIONARIO COMO ENABLED=TRUE. CASO ISSO SEJA FEITO E O ÍNDICE DO FUNCIONÁRIO SEJA MUDADO PARA UM VALOR JÁ EXISTENTE, O SISTEMA QUEBRA
        txtNomeFuncionario.setEnabled(true);
        ftxCPFFuncionario.setEnabled(true);
        //txtEmailFuncionario.setEnabled(true);
        //txtSenhaFuncionario.setEnabled(true);
        txtCodigoFuncionario.setEnabled(false);//FALSE
        
        lblNomeFuncionario.setEnabled(true);
        lblCPFFuncionario.setEnabled(true);
        //lblEmailFuncionario.setEnabled(true);
        //lblSenhaFuncionario.setEnabled(true);
        lblIdFuncionario.setEnabled(true);
        
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterarGerente;
    private javax.swing.JButton btnBuscarFuncionario;
    private javax.swing.JButton btnCancelarGerente;
    private javax.swing.JButton btnExcluirFuncionario;
    private javax.swing.JButton btnNovoFuncionario;
    private javax.swing.JButton btnSalvarFuncionario;
    private javax.swing.JButton btnSalvarGerente;
    private javax.swing.JFormattedTextField ftxCPFFuncionario;
    private javax.swing.JFormattedTextField ftxCPFGerente;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JLabel lblAreaGerente;
    private javax.swing.JLabel lblCPFFuncionario;
    private javax.swing.JLabel lblCPFGerente;
    private javax.swing.JLabel lblControleFuncionarios;
    private javax.swing.JLabel lblDadosGerente;
    private javax.swing.JLabel lblEmailGerente;
    private javax.swing.JLabel lblIdFuncionario;
    private javax.swing.JLabel lblIdGerente;
    private javax.swing.JLabel lblNomeFuncionario;
    private javax.swing.JLabel lblNomeGerente;
    private javax.swing.JLabel lblSenhaGerente;
    private javax.swing.JTable tblControleFuncionariosx;
    private javax.swing.JTextField txtCodigoFuncionario;
    private javax.swing.JTextField txtEmailGerente;
    private javax.swing.JTextField txtIdGerente;
    private javax.swing.JTextField txtNomeFuncionario;
    private javax.swing.JTextField txtNomeGerente;
    private javax.swing.JTextField txtSenhaGerente;
    // End of variables declaration//GEN-END:variables
}
