/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

import classes.Carrinho;
import static classes.Pagamento.listaCarrinhosAntigos;
import javax.swing.table.DefaultTableModel;
import classes.Pagamento;

/**
 *
 * @author Yuri
 */
public class carrinhosAntigos extends javax.swing.JFrame {

    /**
     * Creates new form carrinhosAntigos
     */
    public carrinhosAntigos() {
        initComponents();
        setLocationRelativeTo(null);
        disableCarrinhoFields();
        btnCancelarCarrinho.setEnabled(false);
        carregarTabelaCarrinhosAntigos();
        
    }
    
            public void enableCarrinhoFields(){
            txtNumCarrinho.setEnabled(true);
            txtData.setEnabled(true);
            txtProdutos.setEnabled(true);
            txtTotal.setEnabled(true);
            
            lblNumCarrinho.setEnabled(true);
            lblData.setEnabled(true);
            lblProdutos.setEnabled(true);
            lblTotal.setEnabled(true);
            
        }
            
        public void disableCarrinhoFields(){
            txtNumCarrinho.setEnabled(false);
            txtData.setEnabled(false);
            txtProdutos.setEnabled(false);
            txtTotal.setEnabled(false);
            
            lblNumCarrinho.setEnabled(false);
            lblData.setEnabled(false);
            lblProdutos.setEnabled(false);
            lblTotal.setEnabled(false);
        }

                    
        private void carregarTabelaCarrinhosAntigos() {
            DefaultTableModel modeloTabelaCarrinhosAntigos = new DefaultTableModel(new Object[] {"Num.Carrinho","Data do Pedido","Produtos","Total"},0);
            
            for(int i=0;i<listaCarrinhosAntigos.size();i++){
                Carrinho carrinhoSelecionado = listaCarrinhosAntigos.get(i);

                Object linha[];
                linha = new Object[]{carrinhoSelecionado.getNumCarrinho(),
                    carrinhoSelecionado.getData(),
                    carrinhoSelecionado.mostarProdutos(),
                    carrinhoSelecionado.getTotal()};
                
                modeloTabelaCarrinhosAntigos.addRow(linha);
                
            }
            //Tabela recebe modelo
            tblCarrinhosAntigos.setModel(modeloTabelaCarrinhosAntigos);
            
            tblCarrinhosAntigos.getColumnModel().getColumn(0).setPreferredWidth(3);
            tblCarrinhosAntigos.getColumnModel().getColumn(1).setPreferredWidth(14);
            tblCarrinhosAntigos.getColumnModel().getColumn(2).setPreferredWidth(100);
            tblCarrinhosAntigos.getColumnModel().getColumn(3).setPreferredWidth(5);
            
            
    }
        

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCarrinhosAntigos = new javax.swing.JTable();
        lblCarrinhosAnteriores = new javax.swing.JLabel();
        lblNumCarrinho = new javax.swing.JLabel();
        lblData = new javax.swing.JLabel();
        lblProdutos = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        txtNumCarrinho = new javax.swing.JTextField();
        txtTotal = new javax.swing.JTextField();
        txtData = new javax.swing.JFormattedTextField();
        btnPesquisarCarrinho = new javax.swing.JButton();
        btnCancelarCarrinho = new javax.swing.JButton();
        btnBuscarCarrinho = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtProdutos = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Consultar carrinhos anteriores");

        tblCarrinhosAntigos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "NumCarrinho", "Data do pedido", "Produtos", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Object.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblCarrinhosAntigos);

        lblCarrinhosAnteriores.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblCarrinhosAnteriores.setText("Consultar Carrinhos Antigos");

        lblNumCarrinho.setText("NumCarrinho");

        lblData.setText("Data");

        lblProdutos.setText("Produtos");

        lblTotal.setText("Total");

        txtNumCarrinho.setToolTipText("número do carrinho");

        txtTotal.setToolTipText("valor total");

        try {
            txtData.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtData.setToolTipText("data do pedido");

        btnPesquisarCarrinho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/simbolos/searchmagnifierinterfacesymbol1_79893.png"))); // NOI18N
        btnPesquisarCarrinho.setText("Pesquisar");
        btnPesquisarCarrinho.setToolTipText("pesquisar por carrinho");
        btnPesquisarCarrinho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarCarrinhoActionPerformed(evt);
            }
        });

        btnCancelarCarrinho.setBackground(new java.awt.Color(255, 0, 0));
        btnCancelarCarrinho.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnCancelarCarrinho.setText("Cancelar");
        btnCancelarCarrinho.setToolTipText("cancelar operação");
        btnCancelarCarrinho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarCarrinhoActionPerformed(evt);
            }
        });

        btnBuscarCarrinho.setText("Buscar");

        txtProdutos.setColumns(20);
        txtProdutos.setRows(5);
        jScrollPane2.setViewportView(txtProdutos);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 885, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(91, 91, 91)
                                .addComponent(lblNumCarrinho)
                                .addGap(18, 18, 18)
                                .addComponent(txtNumCarrinho, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblTotal)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(333, 333, 333))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(366, 366, 366)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(lblData)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(lblCarrinhosAnteriores)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(216, 216, 216)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(btnBuscarCarrinho)
                                        .addGap(49, 49, 49)
                                        .addComponent(lblProdutos)
                                        .addGap(18, 18, 18)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(btnPesquisarCarrinho)
                                        .addGap(239, 239, 239)
                                        .addComponent(btnCancelarCarrinho)))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(180, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCarrinhosAnteriores)
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNumCarrinho)
                    .addComponent(txtNumCarrinho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblData)
                    .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTotal)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 27, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblProdutos)
                        .addComponent(btnBuscarCarrinho))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnPesquisarCarrinho)
                    .addComponent(btnCancelarCarrinho))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPesquisarCarrinhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarCarrinhoActionPerformed
        // TODO add your handling code here:
        enableCarrinhoFields();
        btnCancelarCarrinho.setEnabled(true);
        btnPesquisarCarrinho.setEnabled(false);
    }//GEN-LAST:event_btnPesquisarCarrinhoActionPerformed

    private void btnCancelarCarrinhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarCarrinhoActionPerformed
        // TODO add your handling code here:
        disableCarrinhoFields();
        btnPesquisarCarrinho.setEnabled(true);
        btnCancelarCarrinho.setEnabled(false);
    }//GEN-LAST:event_btnCancelarCarrinhoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(carrinhosAntigos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(carrinhosAntigos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(carrinhosAntigos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(carrinhosAntigos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new carrinhosAntigos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarCarrinho;
    private javax.swing.JButton btnCancelarCarrinho;
    private javax.swing.JButton btnPesquisarCarrinho;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblCarrinhosAnteriores;
    private javax.swing.JLabel lblData;
    private javax.swing.JLabel lblNumCarrinho;
    private javax.swing.JLabel lblProdutos;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JTable tblCarrinhosAntigos;
    private javax.swing.JFormattedTextField txtData;
    private javax.swing.JTextField txtNumCarrinho;
    private javax.swing.JTextArea txtProdutos;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
