/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

import classes.Cliente;
import static classes.Cliente.listaClientes;
import static classes.Estoque.estoque;
import classes.Funcionario;
import static classes.Funcionario.listaFuncionarios;
import classes.Gerente;
import classes.Produto;
import javax.swing.JOptionPane;
import static telas.cadastarGerente.listaGerente;
//import static telas.cadastrarCliente.listaClientes;
//import static telas.cadastrarFuncionario.listaFuncionarios;


/**
 *
 * @author Yuri
 */

public class Menu extends javax.swing.JFrame {
    
    static boolean logado = false;
    static String user;// 'gerente','funcionario','cliente'


    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        System.out.println("logado:"+logado);
        System.out.println("user:"+user);
        setLocationRelativeTo(null);
        this.setExtendedState(MAXIMIZED_BOTH);
        verificarLogin(logado, user);
        criarContasIniciais();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    public void criarContasIniciais(){
        if(listaFuncionarios.size()==0 & listaClientes.size()==0 & estoque.size()==0){
        Gerente gerente;
        gerente = new Gerente("admin","000.000.000-00","admin@gmail.com","admin");
        listaGerente.add(gerente);
        Funcionario funcionario;
        funcionario = new Funcionario("func","000.000.000-00","func@gmail.com","func");
        listaFuncionarios.add(funcionario);
        Cliente cliente = new Cliente("user","000.000.000-00","user@gmail.com","user","Pernambuco","10/05/1990","999-9999");
        listaClientes.add(cliente);
        Produto produto1 = new Produto("Eragon","Christopher Paolini","Aventura",15.69,3,"1","Eragon se torna um cavaleiro de Dragão");
        estoque.add(produto1);
            
        }
    }
    public void verificarLogin(boolean logado, String user){
        //  Habilitar/desabilitar botão de Logout
        if(logado==true){
            btnLogout.setVisible(true);
            btnLogin.setVisible(false);
            if(user.equals("cliente")){
                lblLogin.setVisible(true);
                lblLogin.setText("Você entrou como cliente!");
            }else if(user.equals("funcionario")){
                lblLogin.setVisible(true);
                lblLogin.setText("Você entrou como funcionário");
            }else if(user.equals("gerente")){
                lblLogin.setVisible(true);
                lblLogin.setText("Você entrou como gerente");
            }
            }else{
                btnLogout.setVisible(false);
                btnLogin.setVisible(true);
                lblLogin.setVisible(false);
            }
    }
    public void atualizarLogin(){
        //  Habilitar/desabilitar botão de Logout
        if(logado==true){
            btnLogout.setVisible(true);
            btnLogin.setVisible(false);
            if(user.equals("cliente")){
                lblLogin.setVisible(true);
                lblLogin.setText("Você entrou como cliente!");
            }else if(user.equals("funcionario")){
                lblLogin.setVisible(true);
                lblLogin.setText("Você entrou como funcionário");
            }else if(user.equals("gerente")){
                lblLogin.setVisible(true);
                lblLogin.setText("Você entrou como gerente");
            }
            }else{
                btnLogout.setVisible(false);
                btnLogin.setVisible(true);
                lblLogin.setVisible(false);
            }
    }

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblLogin = new javax.swing.JLabel();
        lblBookStockManager = new javax.swing.JLabel();
        btnAtualizarEstoque = new javax.swing.JToggleButton();
        btnVerCarrinho = new javax.swing.JButton();
        btnPesquisar = new javax.swing.JButton();
        btnFuncionario = new javax.swing.JButton();
        btnGerente = new javax.swing.JButton();
        btnCliente = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        btnLogin = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblLogo = new javax.swing.JLabel();
        lblImagem = new javax.swing.JLabel();

        jMenuItem1.setText("jMenuItem1");

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu principal");
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/imagens/logo_digitalbooks03_small3.png")).getImage());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblLogin.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        lblLogin.setForeground(new java.awt.Color(255, 0, 0));
        lblLogin.setText("Você entrou como cliente");
        jPanel1.add(lblLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, -1, -1));

        lblBookStockManager.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        lblBookStockManager.setForeground(new java.awt.Color(255, 255, 255));
        lblBookStockManager.setText("BookStock");
        jPanel1.add(lblBookStockManager, new org.netbeans.lib.awtextra.AbsoluteConstraints(1580, 210, -1, -1));

        btnAtualizarEstoque.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        btnAtualizarEstoque.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/simbolos/business_inventory_maintenance_product_box_boxes_2326_64.png"))); // NOI18N
        btnAtualizarEstoque.setText("Atualizar Estoque");
        btnAtualizarEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarEstoqueActionPerformed(evt);
            }
        });
        jPanel1.add(btnAtualizarEstoque, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 310, 340, 80));

        btnVerCarrinho.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        btnVerCarrinho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/simbolos/4105931-add-to-cart-buy-cart-sell-shop-shopping-cart_113919_64.png"))); // NOI18N
        btnVerCarrinho.setText("Ver carrinho");
        btnVerCarrinho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerCarrinhoActionPerformed(evt);
            }
        });
        jPanel1.add(btnVerCarrinho, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 190, 340, 90));

        btnPesquisar.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        btnPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/simbolos/searchmagnifierinterfacesymbol1_79893_64.png"))); // NOI18N
        btnPesquisar.setText("Buscar Produto");
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });
        jPanel1.add(btnPesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 190, 330, 90));

        btnFuncionario.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        btnFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/simbolos/technicalsupport_support_representative_person_people_man_1641_64.png"))); // NOI18N
        btnFuncionario.setText("Funcionário");
        btnFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFuncionarioActionPerformed(evt);
            }
        });
        jPanel1.add(btnFuncionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 310, 320, 80));

        btnGerente.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        btnGerente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/simbolos/customer_person_people_man_you_1625_64.png"))); // NOI18N
        btnGerente.setText("Gerente");
        btnGerente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGerenteActionPerformed(evt);
            }
        });
        jPanel1.add(btnGerente, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 310, 330, 80));

        btnCliente.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        btnCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/simbolos/person_user_customer_man_male_man_boy_people_1687_64.png"))); // NOI18N
        btnCliente.setText("Cliente");
        btnCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClienteActionPerformed(evt);
            }
        });
        jPanel1.add(btnCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 190, 320, 90));

        btnLogout.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/simbolos/logout_90894_64.png"))); // NOI18N
        btnLogout.setText("Logout");
        btnLogout.setToolTipText("Sair do sistema");
        btnLogout.setBorder(null);
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        jPanel1.add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 200, 70));

        btnLogin.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        btnLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/simbolos/login-square-arrow-button-outline_icon-icons.com_73220_64.png"))); // NOI18N
        btnLogin.setText("Login");
        btnLogin.setToolTipText("Entrar no sistema");
        btnLogin.setBorder(null);
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        jPanel1.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 200, 70));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Manager");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1600, 260, -1, -1));

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/livro01.png"))); // NOI18N
        jPanel1.add(lblLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(1460, 0, 390, 210));

        lblImagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/madeira-background.jpg"))); // NOI18N
        jPanel1.add(lblImagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 1190));
        lblImagem.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        logado=false;
        user="";
        verificarLogin(logado,user);
        JOptionPane.showMessageDialog(null,"Você acabou de sair do sistema", "Mensagem",JOptionPane.PLAIN_MESSAGE);
        

    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
telaLogin tela = new telaLogin();
tela.setVisible(true);

// Event-driven approach could be used here to detect successful login
tela.addWindowListener(new java.awt.event.WindowAdapter() {
    @Override
    public void windowClosed(java.awt.event.WindowEvent windowEvent) {
        verificarLogin(logado,user);
    }
});
        
        this.setVisible(false);
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClienteActionPerformed
        // TODO add your handling code here:
        verificarLogin(logado,user);

        if(logado==true){
            if(user.equals("gerente") || user.equals("funcionario")){
                JOptionPane.showMessageDialog(null,"Você tem acesso a criar nova conta de cliente","Notificação de acesso a cliente",JOptionPane.ERROR_MESSAGE);
                new cadastrarCliente().setVisible(true);
            }else{
                new areaCliente().setVisible(true);
            }
        }else{
            JOptionPane.showMessageDialog(null,"Você não entrou no sistema. Crie uma nova conta como Cliente", "Mensagem",JOptionPane.PLAIN_MESSAGE);

            new cadastrarCliente().setVisible(true);
        }

    }//GEN-LAST:event_btnClienteActionPerformed

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        // TODO add your handling code here:
        new verProdutos().setVisible(true);
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void btnFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFuncionarioActionPerformed
        // TODO add your handling code here:
        verificarLogin(logado,user);

        
        if(logado==true){
            if( user.equals("gerente")){
            new cadastrarFuncionario().setVisible(true);
            }else if(user.equals("funcionario")){
                    new areaFuncionario().setVisible(true);
                    }
            else{
            JOptionPane.showMessageDialog(null,"Não é possível acessar esse recurso!","Erro ao acessar funcionário",JOptionPane.ERROR_MESSAGE);
        }
        }else{
            JOptionPane.showMessageDialog(null,"Não é possível acessar esse recurso!","Erro ao acessar funcionário",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnFuncionarioActionPerformed

    private void btnGerenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGerenteActionPerformed
        // TODO add your handling code here:
        
        verificarLogin(logado,user);
        if(logado==true){
            if(user.equals("gerente")){
                new areaGerente().setVisible(true);
            }else{
            JOptionPane.showMessageDialog(null,"Não é possível acessar esse recurso!","Erro ao acessar gerente",JOptionPane.ERROR_MESSAGE);

        }
        }else{
            JOptionPane.showMessageDialog(null,"Não é possível acessar esse recurso!","Erro ao acessar gerente",JOptionPane.ERROR_MESSAGE);

        }

    }//GEN-LAST:event_btnGerenteActionPerformed

    private void btnVerCarrinhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerCarrinhoActionPerformed
        // TODO add your handling code here:
        //Verifica se o usuário está logado no sistema
        verificarLogin(logado,user);

        if(logado==true){
            new verCarrinho().setVisible(true);
        }else{
       JOptionPane.showMessageDialog(null,"Entre com uma conta para acessar seu carrinho!","Erro ao acessar carrinho",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnVerCarrinhoActionPerformed

    private void btnAtualizarEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarEstoqueActionPerformed
        // TODO add your handling code here:
        verificarLogin(logado,user);
        if(logado==true){
            if(user.equals("funcionario") || user.equals("gerente") ){
                new ControleEstoque().setVisible(true);
            }else{//Caso esteja como cliente
                JOptionPane.showMessageDialog(null,"Não é possível acessar esse recurso!","Erro ao acessar Controle de Estoque",JOptionPane.ERROR_MESSAGE);

            }
        }else{//Caso não esteja logado
                JOptionPane.showMessageDialog(null,"Não é possível acessar esse recurso!","Erro ao acessar Controle de Estoque",JOptionPane.ERROR_MESSAGE);
            }
    }//GEN-LAST:event_btnAtualizarEstoqueActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnAtualizarEstoque;
    private javax.swing.JButton btnCliente;
    private javax.swing.JButton btnFuncionario;
    private javax.swing.JButton btnGerente;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JButton btnVerCarrinho;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblBookStockManager;
    private javax.swing.JLabel lblImagem;
    private javax.swing.JLabel lblLogin;
    private javax.swing.JLabel lblLogo;
    // End of variables declaration//GEN-END:variables
}
