/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

/**
 *
 * @author Yuri
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        
        //setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblBookStockManager = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jButton6 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        btnLogin = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblLogo = new javax.swing.JLabel();
        lblImagem = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmnCadastrar = new javax.swing.JMenu();
        mntCliente = new javax.swing.JMenuItem();
        mntFuncionario = new javax.swing.JMenuItem();
        mntGerente = new javax.swing.JMenuItem();
        jmnFazerConsulta = new javax.swing.JMenu();
        mntBuscar = new javax.swing.JMenuItem();
        mntAtualizarEstoque = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jmnPáginasUsuário = new javax.swing.JMenu();
        mntAreaCliente = new javax.swing.JMenuItem();
        mntAreaFuncionario = new javax.swing.JMenuItem();
        mntAreaGerente = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu principal");
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/imagens/logo_digitalbooks03_small3.png")).getImage());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblBookStockManager.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblBookStockManager.setForeground(new java.awt.Color(255, 255, 255));
        lblBookStockManager.setText("BookStock");
        jPanel1.add(lblBookStockManager, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 110, -1, -1));

        jToggleButton1.setText("Atualizar Estoque");
        jPanel1.add(jToggleButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 370, -1, -1));

        jButton6.setText("Ver carrinho");
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 320, -1, -1));

        jButton5.setText("Buscar Produto");
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 260, -1, -1));

        jButton3.setText("Funcionário");
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 310, -1, -1));

        jButton4.setText("Gerente");
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 370, -1, -1));

        jButton2.setText("Cliente");
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, -1, -1));

        btnLogout.setBackground(new java.awt.Color(102, 102, 102));
        btnLogout.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(255, 255, 255));
        btnLogout.setText("Logout");
        btnLogout.setToolTipText("Sair do sistema");
        btnLogout.setBorder(null);
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        jPanel1.add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 111, -1));

        btnLogin.setBackground(new java.awt.Color(102, 102, 102));
        btnLogin.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin.setText("Login");
        btnLogin.setToolTipText("Entrar no sistema");
        btnLogin.setBorder(null);
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        jPanel1.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 108, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Manager");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 130, -1, -1));

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/logo_digitalbooks03_small3.png"))); // NOI18N
        jPanel1.add(lblLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 0, 140, 110));

        lblImagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/background.jpg"))); // NOI18N
        jPanel1.add(lblImagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 660));

        jmnCadastrar.setText("Cadastrar");
        jmnCadastrar.setToolTipText("Cadastrar um  novo usuário");

        mntCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/simbolos/person_user_customer_man_male_man_boy_people_1687 (1).png"))); // NOI18N
        mntCliente.setText("Cliente");
        mntCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mntClienteActionPerformed(evt);
            }
        });
        jmnCadastrar.add(mntCliente);

        mntFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/simbolos/technicalsupport_support_representative_person_people_man_1641.png"))); // NOI18N
        mntFuncionario.setText("Funcionário");
        mntFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mntFuncionarioActionPerformed(evt);
            }
        });
        jmnCadastrar.add(mntFuncionario);

        mntGerente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/simbolos/customer_person_people_man_you_1625.png"))); // NOI18N
        mntGerente.setText("Gerente");
        mntGerente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mntGerenteActionPerformed(evt);
            }
        });
        jmnCadastrar.add(mntGerente);

        jMenuBar1.add(jmnCadastrar);

        jmnFazerConsulta.setText("Fazer Consulta");
        jmnFazerConsulta.setToolTipText("Consultar um produto");

        mntBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/simbolos/searchmagnifierinterfacesymbol1_79893.png"))); // NOI18N
        mntBuscar.setText("Buscar por produto");
        mntBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mntBuscarActionPerformed(evt);
            }
        });
        jmnFazerConsulta.add(mntBuscar);

        mntAtualizarEstoque.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/simbolos/4105931-add-to-cart-buy-cart-sell-shop-shopping-cart_113919.png"))); // NOI18N
        mntAtualizarEstoque.setText("Atualizar Estoque");
        mntAtualizarEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mntAtualizarEstoqueActionPerformed(evt);
            }
        });
        jmnFazerConsulta.add(mntAtualizarEstoque);

        jMenuItem2.setText("Ver meu Carrinho");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jmnFazerConsulta.add(jMenuItem2);

        jMenuBar1.add(jmnFazerConsulta);

        jmnPáginasUsuário.setText("Páginas de usuário");
        jmnPáginasUsuário.setToolTipText("Acessar páginas de usuário");

        mntAreaCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/simbolos/person_user_customer_man_male_man_boy_people_1687 (1).png"))); // NOI18N
        mntAreaCliente.setText("Área do Cliente");
        mntAreaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mntAreaClienteActionPerformed(evt);
            }
        });
        jmnPáginasUsuário.add(mntAreaCliente);

        mntAreaFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/simbolos/technicalsupport_support_representative_person_people_man_1641.png"))); // NOI18N
        mntAreaFuncionario.setText("Área do funcionário");
        mntAreaFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mntAreaFuncionarioActionPerformed(evt);
            }
        });
        jmnPáginasUsuário.add(mntAreaFuncionario);

        mntAreaGerente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/simbolos/customer_person_people_man_you_1625.png"))); // NOI18N
        mntAreaGerente.setText("Área do Gerente");
        mntAreaGerente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mntAreaGerenteActionPerformed(evt);
            }
        });
        jmnPáginasUsuário.add(mntAreaGerente);

        jMenuBar1.add(jmnPáginasUsuário);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mntGerenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mntGerenteActionPerformed
        // TODO add your handling code here:
        new cadastarGerente().setVisible(true);
    }//GEN-LAST:event_mntGerenteActionPerformed

    private void mntAreaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mntAreaClienteActionPerformed
        // TODO add your handling code here:
        new areaCliente().setVisible(true);
    }//GEN-LAST:event_mntAreaClienteActionPerformed

    private void mntFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mntFuncionarioActionPerformed
        // TODO add your handling code here:
        new cadastrarFuncionario().setVisible(true);
    }//GEN-LAST:event_mntFuncionarioActionPerformed

    private void mntClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mntClienteActionPerformed
        // TODO add your handling code here:
        new cadastrarCliente().setVisible(true);
    }//GEN-LAST:event_mntClienteActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void mntAreaFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mntAreaFuncionarioActionPerformed
        // TODO add your handling code here:
        new areaFuncionario().setVisible(true);
    }//GEN-LAST:event_mntAreaFuncionarioActionPerformed

    private void mntAreaGerenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mntAreaGerenteActionPerformed
        // TODO add your handling code here:
        new areaGerente().setVisible(true);
    }//GEN-LAST:event_mntAreaGerenteActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        new telaLogin().setVisible(true);
    }//GEN-LAST:event_btnLoginActionPerformed

    private void mntAtualizarEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mntAtualizarEstoqueActionPerformed
        // TODO add your handling code here:
        new ControleEstoque().setVisible(true);
    }//GEN-LAST:event_mntAtualizarEstoqueActionPerformed

    private void mntBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mntBuscarActionPerformed
        // TODO add your handling code here:
        new verProdutos().setVisible(true);
    }//GEN-LAST:event_mntBuscarActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        new verCarrinho().setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JMenu jmnCadastrar;
    private javax.swing.JMenu jmnFazerConsulta;
    private javax.swing.JMenu jmnPáginasUsuário;
    private javax.swing.JLabel lblBookStockManager;
    private javax.swing.JLabel lblImagem;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JMenuItem mntAreaCliente;
    private javax.swing.JMenuItem mntAreaFuncionario;
    private javax.swing.JMenuItem mntAreaGerente;
    private javax.swing.JMenuItem mntAtualizarEstoque;
    private javax.swing.JMenuItem mntBuscar;
    private javax.swing.JMenuItem mntCliente;
    private javax.swing.JMenuItem mntFuncionario;
    private javax.swing.JMenuItem mntGerente;
    // End of variables declaration//GEN-END:variables
}
