/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

/**
 *
 * @author Yuri
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        
        //setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        lblBookStockManager = new javax.swing.JLabel();
        lblLogo = new javax.swing.JLabel();
        lblImagem = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnLogin = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmnCadastrar = new javax.swing.JMenu();
        mntCliente = new javax.swing.JMenuItem();
        mntFuncionario = new javax.swing.JMenuItem();
        mntGerente = new javax.swing.JMenuItem();
        jmnFazerConsulta = new javax.swing.JMenu();
        mntBuscar = new javax.swing.JMenuItem();
        mntAtualizarEstoque = new javax.swing.JMenuItem();
        jmnPáginasUsuário = new javax.swing.JMenu();
        mntAreaCliente = new javax.swing.JMenuItem();
        mntAreaFuncionario = new javax.swing.JMenuItem();
        mntAreaGerente = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu principal");

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblBookStockManager.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblBookStockManager.setForeground(new java.awt.Color(255, 255, 255));
        lblBookStockManager.setText("BookStockManager");
        jPanel1.add(lblBookStockManager, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 420, -1, -1));

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/logo_digitalbooks.png"))); // NOI18N
        jPanel1.add(lblLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 0, 250, 220));

        lblImagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/background.jpg"))); // NOI18N
        jPanel1.add(lblImagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 0, 860, 660));

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));
        jPanel2.setForeground(new java.awt.Color(102, 102, 102));

        btnLogin.setBackground(new java.awt.Color(102, 102, 102));
        btnLogin.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin.setText("Login");
        btnLogin.setToolTipText("Entrar no sistema");
        btnLogin.setBorder(null);
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(102, 102, 102));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/simbolos/customer_person_people_man_you_1625.png"))); // NOI18N
        jButton1.setBorder(null);

        btnLogout.setBackground(new java.awt.Color(102, 102, 102));
        btnLogout.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(255, 255, 255));
        btnLogout.setText("Logout");
        btnLogout.setToolTipText("Sair do sistema");
        btnLogout.setBorder(null);
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)
                        .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 535, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLogin)
                    .addComponent(btnLogout))
                .addGap(17, 17, 17))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 660));

        jmnCadastrar.setText("Cadastrar");
        jmnCadastrar.setToolTipText("Cadastrar um  novo usuário");

        mntCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/simbolos/person_user_customer_man_male_man_boy_people_1687 (1).png"))); // NOI18N
        mntCliente.setText("Cliente");
        mntCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mntClienteActionPerformed(evt);
            }
        });
        jmnCadastrar.add(mntCliente);

        mntFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/simbolos/technicalsupport_support_representative_person_people_man_1641.png"))); // NOI18N
        mntFuncionario.setText("Funcionário");
        mntFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mntFuncionarioActionPerformed(evt);
            }
        });
        jmnCadastrar.add(mntFuncionario);

        mntGerente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/simbolos/customer_person_people_man_you_1625.png"))); // NOI18N
        mntGerente.setText("Gerente");
        mntGerente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mntGerenteActionPerformed(evt);
            }
        });
        jmnCadastrar.add(mntGerente);

        jMenuBar1.add(jmnCadastrar);

        jmnFazerConsulta.setText("Fazer Consulta");
        jmnFazerConsulta.setToolTipText("Consultar um produto");

        mntBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/simbolos/searchmagnifierinterfacesymbol1_79893.png"))); // NOI18N
        mntBuscar.setText("Buscar por produto");
        jmnFazerConsulta.add(mntBuscar);

        mntAtualizarEstoque.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/simbolos/4105931-add-to-cart-buy-cart-sell-shop-shopping-cart_113919.png"))); // NOI18N
        mntAtualizarEstoque.setText("Atualizar Estoque");
        jmnFazerConsulta.add(mntAtualizarEstoque);

        jMenuBar1.add(jmnFazerConsulta);

        jmnPáginasUsuário.setText("Páginas de usuário");
        jmnPáginasUsuário.setToolTipText("Acessar páginas de usuário");

        mntAreaCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/simbolos/person_user_customer_man_male_man_boy_people_1687 (1).png"))); // NOI18N
        mntAreaCliente.setText("Área do Cliente");
        mntAreaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mntAreaClienteActionPerformed(evt);
            }
        });
        jmnPáginasUsuário.add(mntAreaCliente);

        mntAreaFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/simbolos/technicalsupport_support_representative_person_people_man_1641.png"))); // NOI18N
        mntAreaFuncionario.setText("Área do funcionário");
        mntAreaFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mntAreaFuncionarioActionPerformed(evt);
            }
        });
        jmnPáginasUsuário.add(mntAreaFuncionario);

        mntAreaGerente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/simbolos/customer_person_people_man_you_1625.png"))); // NOI18N
        mntAreaGerente.setText("Área do Gerente");
        mntAreaGerente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mntAreaGerenteActionPerformed(evt);
            }
        });
        jmnPáginasUsuário.add(mntAreaGerente);

        jMenuBar1.add(jmnPáginasUsuário);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1201, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mntGerenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mntGerenteActionPerformed
        // TODO add your handling code here:
        new cadastarGerente().setVisible(true);
    }//GEN-LAST:event_mntGerenteActionPerformed

    private void mntAreaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mntAreaClienteActionPerformed
        // TODO add your handling code here:
        new areaCliente().setVisible(true);
    }//GEN-LAST:event_mntAreaClienteActionPerformed

    private void mntFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mntFuncionarioActionPerformed
        // TODO add your handling code here:
        new cadastrarFuncionario().setVisible(true);
    }//GEN-LAST:event_mntFuncionarioActionPerformed

    private void mntClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mntClienteActionPerformed
        // TODO add your handling code here:
        new cadastrarCliente().setVisible(true);
    }//GEN-LAST:event_mntClienteActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void mntAreaFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mntAreaFuncionarioActionPerformed
        // TODO add your handling code here:
        new areaFuncionario().setVisible(true);
    }//GEN-LAST:event_mntAreaFuncionarioActionPerformed

    private void mntAreaGerenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mntAreaGerenteActionPerformed
        // TODO add your handling code here:
        new areaGerente().setVisible(true);
    }//GEN-LAST:event_mntAreaGerenteActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton jButton1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JMenu jmnCadastrar;
    private javax.swing.JMenu jmnFazerConsulta;
    private javax.swing.JMenu jmnPáginasUsuário;
    private javax.swing.JLabel lblBookStockManager;
    private javax.swing.JLabel lblImagem;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JMenuItem mntAreaCliente;
    private javax.swing.JMenuItem mntAreaFuncionario;
    private javax.swing.JMenuItem mntAreaGerente;
    private javax.swing.JMenuItem mntAtualizarEstoque;
    private javax.swing.JMenuItem mntBuscar;
    private javax.swing.JMenuItem mntCliente;
    private javax.swing.JMenuItem mntFuncionario;
    private javax.swing.JMenuItem mntGerente;
    // End of variables declaration//GEN-END:variables
}
